version: '3.8'

services:
  reweb:
    image: reweb:latest
    build:
      context: ./reweb
      args:
        ENV_FILE: .dev.env
    container_name: reweb
    restart: always
    ports:
      - "3001:3001"
    networks:
      - reposter-net

networks:
  reposter-net: